#!/bin/bash
#
# [QuickBox Installation Script]
#
# GitHub:   https://github.com/QuickBox/QuickBox
# Author:   QuickBox.IO
# URL:      https://plaza.quickbox.io
#
# QuickBox Copyright (C) 2017 QuickBox.io
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
#Script Console Colors
black=$(tput setaf 0); red=$(tput setaf 1); green=$(tput setaf 2); yellow=$(tput setaf 3);
blue=$(tput setaf 4); magenta=$(tput setaf 5); cyan=$(tput setaf 6); white=$(tput setaf 7);
on_red=$(tput setab 1); on_green=$(tput setab 2); on_yellow=$(tput setab 3); on_blue=$(tput setab 4);
on_magenta=$(tput setab 5); on_cyan=$(tput setab 6); on_white=$(tput setab 7); bold=$(tput bold);
dim=$(tput dim); underline=$(tput smul); reset_underline=$(tput rmul); standout=$(tput smso);
reset_standout=$(tput rmso); normal=$(tput sgr0); alert=${white}${on_red}; title=${standout};
sub_title=${bold}${yellow}; repo_title=${black}${on_green}; message_title=${white}${on_magenta}
baihuangse=${white}${on_yellow}; bailanse=${white}${on_blue}; bailvse=${white}${on_green};
baiqingse=${white}${on_cyan}; baihongse=${white}${on_red}; baizise=${white}${on_magenta};
heibaise=${black}${on_white}; heihuangse=${on_yellow}${black}
jiacu=${normal}${bold}
shanshuo=$(tput blink); wuguangbiao=$(tput civis); guangbiao=$(tput cnorm)
#################################################################################
function _string() { perl -le 'print map {(a..z,A..Z,0..9)[rand 62] } 0..pop' 15 ; }
#################################################################################

sshport=$(grep -P '^[#\s]*Port ' /etc/ssh/sshd_config | sed 's/[^0-9]*//g')

### 输入自己想要的软件版本 ###
function _inputversion() {
echo -e "\n${baihongse}${bold} ATTENTION ${normal} ${bold}Make sure to input the correct version${normal}"
read -ep "${bold}${yellow}Input the version you want: ${cyan}" inputversion; echo -n "${normal}" ; }

# 增加 swap
function _use_swap() { dd if=/dev/zero of=/root/.swapfile bs=1M count=1024  >>"${OUTTO}" 2>&1 ;  mkswap /root/.swapfile  >>"${OUTTO}" 2>&1 ;  swapon /root/.swapfile  >>"${OUTTO}" 2>&1 ;  swapon -s  >>"${OUTTO}" 2>&1 ;  }

# 关掉之前开的 swap
function _disable_swap() { swapoff /root/.swapfile  >>"${OUTTO}" 2>&1 ;  rm -f /.swapfile >>"${OUTTO}" 2>&1 ; }

# 初始化
function _init() {
apt-get install -y git lsb-release locales || { echo -e "\n${bold}Please run apt-get update or check your apt sources list!${normal}\n" ; exit 1 ; }
TR_repo_ver=` apt-cache policy transmission-daemon | grep -B1 http | grep -Eo "[23]\.[0-9.]+" | head -n1 `
[[ ! -d /etc/QuickBox ]] && git clone --depth=1 -b AniverseMod https://github.com/Aniverse/QB /etc/QuickBox
[[ ! -d /etc/QuickBox ]] && { echo -e "\n${bold}${baihongse} ERROR ${jiacu}Could not clone QuickBox repo!${normal}\n" ; exit 1 ; } ; }


function _bashrc() {
  cp ${local_setup}templates/bashrc.template /root/.bashrc
  profile="/root/.profile"
  if [ ! -f $profile ]; then
    cp ${local_setup}templates/profile.template /root/.profile
  fi
}

# intro function (1)
function _intro() {
  clear
  DISTRO=$(lsb_release -is)
  RELEASE=$(lsb_release -rs)
  CODENAME=$(lsb_release -cs)
  SETNAME=$(lsb_release -rc)
  echo
  echo
  echo "[${repo_title}QuickBox${normal}] ${title} Aniverse Mod Installation ${normal} "
  echo
  echo "   ${title}              Heads Up!              	    ${normal} "
  echo "   ${message_title}  QuickBox works with the following  ${normal} "
  echo "   ${message_title}  Ubuntu 16.04 | Debian 8            ${normal} "
  echo
  echo
  echo "${green}Checking distribution ...${normal}"
  if [ ! -x  /usr/bin/lsb_release ]; then
    echo "It looks like you are running $DISTRO, which is not supported by QuickBox."
    echo "Exiting..."
    exit 1
  fi
  echo
  if [[ ! "$DISTRO" =~ ("Ubuntu"|"Debian") ]]; then
    echo "$DISTRO: ${alert} It looks like you are running $DISTRO, which is not supported by QuickBox ${normal} "
    echo 'Exiting...'
    exit 1
  elif [[ ! "$CODENAME" =~ ("xenial"|"jessie") ]]; then
    echo "Oh drats! You do not appear to be running a supported $DISTRO release."
    echo "${bold}$SETNAME${normal}"
    echo 'Exiting...'
    exit 1
  fi
}

# check if root function (2)
function _checkroot() {
  if [[ $EUID != 0 ]]; then
    echo 'This script must be run with root privileges.'
    echo 'Exiting...'
    exit 1
  fi
  echo "${green}Congrats! You're running as root. Let's continue${normal} ... "
  echo
}

function _checkkernel() {
  grsec=$(uname -a | grep -i grs)
  if [[ -n $grsec ]]; then
    echo -e "Your server is currently running with kernel version: $(uname -r)"
    echo -e "Kernels with ${bold}grsec${normal} are not supported"
    echo -ne "${bold}${yellow}Would you like QuickBox to install the distribution kernel?${normal} (Default: ${green}${bold}Y${normal}) "; read input
      case $input in
        [yY] | [yY][Ee][Ss] | "" ) kernel=yes; echo "Your distribution's default kernel will be installed. A reboot will be ${bold}required${normal}."  ;;
        [nN] | [nN][Oo] ) echo "Installer will not continue. Exiting ... "; exit 0 ;;
      *) kernel=yes; echo "Your distribution's default kernel will be installed. A reboot will be ${bold}required${normal}."  ;;
      esac
      if [[ $kernel == yes ]]; then
        if [[ $DISTRO == Ubuntu ]]; then
          apt-get install -q -y linux-image-generic >>"${OUTTO}" 2>&1
        elif [[ $DISTRO == Debian ]]; then
          arch=$(uname -m)
          if [[ $arch =~ ("i686"|"i386") ]]; then
            apt-get install -q -y linux-image-686 >>"${OUTTO}" 2>&1
          elif [[ $arch == x86_64 ]]; then
            apt-get install -q -y linux-image-amd64 >>"${OUTTO}" 2>&1
          fi
        fi
        mv /etc/grub.d/06_OVHkernel /etc/grub.d/25_OVHkernel
        update-grub >>"${OUTTO}" 2>&1
      fi
  fi
}

# check if create log function (3)
function _logcheck() {
  echo -ne "${bold}${yellow}Do you wish to write to a log file?${normal} (Default: ${green}${bold}Y${normal}) "; read input
    case $input in
      [yY] | [yY][Ee][Ss] | "" ) OUTTO="/root/quickbox.$PPID.log";echo "${bold}Output is being sent to /root/quickbox.${magenta}$PPID${normal}${bold}.log${normal}" ;;
      [nN] | [nN][Oo] ) OUTTO="/dev/null 2>&1";echo "${cyan}NO output will be logged${normal}" ;;
    *) OUTTO="/root/quickbox.$PPID.log";echo "${bold}Output is being sent to /root/quickbox.${magenta}$PPID${normal}${bold}.log${normal}" ;;
    esac
  if [[ ! -d /root/tmp ]]; then
    sed -i 's/noexec,//g' /etc/fstab
    mount -o remount /tmp >>"${OUTTO}" 2>&1
  fi
}

# setting system hostname function (7)
function _hostname() {
echo -ne "Please enter a hostname for this server (${bold}Hit ${standout}${green}ENTER${normal} to make no changes${normal}): " ; read input
if [[ -z $input ]]; then
        echo "No hostname supplied, no changes made!!"
else
        hostname ${input}
        echo "${input}">/etc/hostname
        echo "127.0.0.1 ${input}">/etc/hosts
        echo "Hostname set to ${input}"
fi
echo
}

################################################################################
#              RESERVED FOR LETS ENCRYPT SSL INSTALL FUNCTION                  #
################################################################################

function _askquota() {
  echo -ne "${bold}${yellow}Do you wish to use user quotas?${normal} (Default: ${green}${bold}N${normal}) "; read input
    case $input in
      [yY] | [yY][Ee][Ss]) quota="yes";echo "${bold}Quotas will be installed${normal}" ;;
      [nN] | [nN][Oo] | "" ) quota="no";echo "${cyan}Quotas will not be installed${normal}" ;;
    *) quota="no";echo "${bold}Quotas will not be installed${normal}" ;;
    esac
}

# primary partition question
function _askpartition() {
  if [[ $quota == yes ]]; then
  echo
  echo "##################################################################################"
  echo "#${bold} By default the QuickBox script will initiate a build using ${green}/${normal} ${bold}as the${normal}"
  echo "#${bold} primary partition for mounting quotas.${normal}"
  echo "#"
  echo "#${bold} Some providers, such as OVH and SYS force ${green}/home${normal} ${bold}as the primary mount ${normal}"
  echo "#${bold} on their server setups. So if you have an OVH or SYS server and have not"
  echo "#${bold} modified your partitions, it is safe to choose option ${yellow}2)${normal} ${bold}below.${normal}"
  echo "#"
  echo "#${bold} If you are not sure:${normal}"
  echo "#${bold} I have listed out your current partitions below. Your mountpoint will be"
  echo "#${bold} listed as ${green}/home${normal} ${bold}or ${green}/${normal}${bold}. ${normal}"
  echo "#"
  echo "#${bold} Typically, the partition with the most space assigned is your default.${normal}"
  echo "##################################################################################"
  echo
  lsblk
  echo
  echo -e "${bold}${yellow}1)${normal} / - ${green}root mount${normal}"
  echo -e "${bold}${yellow}2)${normal} /home - ${green}home mount${normal}"
  echo -ne "${bold}${yellow}What is your mount point for user quotas?${normal} (Default ${green}1${normal}): "; read version
  case $version in
    1 | "") primaryroot=root  ;;
    2) primaryroot=home  ;;
    *) primaryroot=root ;;
  esac
  echo "Using ${green}$primaryroot mount${normal} for quotas"
  echo
fi
}

function _askcontinue() {
  echo
  echo "Press ${standout}${green}ENTER${normal} when you're ready to begin or ${standout}${red}Ctrl+Z${normal} to cancel" ;read input
  echo
}

# This function blocks an insecure port 1900 that may lead to
# DDoS masked attacks. Only remove this function if you absolutely
# need port 1900. In most cases, this is a junk port.
function _ssdpblock() {
  iptables -I INPUT 1 -p udp -m udp --dport 1900 -j DROP
}

# setting locale function (6)
function _locale() {
echo 'LANGUAGE="en_US.UTF-8"' >> /etc/default/locale
echo 'LC_ALL="en_US.UTF-8"' >> /etc/default/locale
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
  if [[ -e /usr/sbin/locale-gen ]]; then locale-gen >>"${OUTTO}" 2>&1
  else
    locale-gen >>"${OUTTO}" 2>&1
    export LANG="en_US.UTF-8"
    export LC_ALL="en_US.UTF-8"
    export LANGUAGE="en_US.UTF-8"
  fi
}

function _askservices() {
  DISTRO=$(lsb_release -is)
  RELEASE=$(lsb_release -rs)
  CODENAME=$(lsb_release -cs)
  SETNAME=$(lsb_release -rc)
  echo "You are running $DISTRO $CODENAME"
  echo "This distribution has support for systemd services. "
  echo "Would you like to enable? (recommended) (Default: ${green}${bold}Y${normal})"; read input
    case $input in
      [yY] | [yY][Ee][Ss] | "" ) cron="no";echo "${bold}Using systemd for process management${normal}" ;;
      [nN] | [nN][Oo] ) cron="yes";echo "${cyan}Cron will manage your processes${normal}" ;;
    *) cron="no";echo "${bold}Using systemd for process management${normal}" ;;
    esac
  echo
}

# ask what rtorrent version (8)
function _askdashtheme() {
  echo -e "1) QuickBox - ${green}smoked${normal} :: Dark theme"
  echo -e "2) QuickBox - ${green}defaulted${normal} :: Light theme"
  echo -ne "${bold}${yellow}Pick your QuickBox Dashboard Theme${normal} (Default ${green}1${normal}): "; read version
  case $version in
    1 | "") dash_theme=smoked  ;;
    2) dash_theme=defaulted  ;;
    *) dash_theme=smoked ;;
  esac
  echo "We will be using QuickBox Theme : ${green}$dash_theme${normal}"
  echo
}

# ask what rtorrent version (8)
function _askrtorrent() {
  echo -e "${green}01)${normal} rtorrent ${green}0.9.6 (with ipv6 support)${normal}"
  echo -e "${green}02)${normal} rtorrent ${green}0.9.4 (with ipv6 support)${normal}"
  echo -e "${green}03)${normal} rtorrent ${green}0.9.3${normal}"
  echo -ne "${bold}${yellow}Which version of rtorrent do you want?${normal} (Default ${green}02${normal}): "; read -e version
  case $version in
    1) RTVERSION=0.9.6;LTORRENT=0.13.6  ;;
    2 | "") RTVERSION=0.9.4;LTORRENT=0.13.4  ;;
    3) RTVERSION=0.9.3;LTORRENT=0.13.3 ;;
    *) RTVERSION=0.9.4;LTORRENT=0.13.4  ;;
  esac
  echo "${bold}${baiqingse}rTorrent $RTVERSION${normal} ${bold}will be installed${normal}"
  echo
}

# ask deluge version (if wanted) (8.1)
function _askdeluge() {
echo -e "${green}01)${normal} Deluge ${green}1.3.9${normal}"
echo -e "${green}02)${normal} Deluge ${green}1.3.13${normal}"
echo -e "${green}03)${normal} Deluge ${green}1.3.14${normal}"
echo -e "${green}04)${normal} Deluge ${green}1.3.15${normal}"
echo -e "${green}21)${normal} Deluge ${green}1.3.15 (Skip hash check)${normal}"
echo -e "${green}30)${normal} Select another version"
echo -ne "${bold}${yellow}Which version of Deluge do you want?${normal} (Default ${green}04${normal}): " ; read -e version

case $version in
    01 | 1) DEVERSION=1.3.9 ;;
    02 | 2) DEVERSION=1.3.13 ;;
    03 | 3) DEVERSION=1.3.14 ;;
    04 | 4) DEVERSION=1.3.15 ;;
    21) DEVERSION='1.3.15 (Skip hash check)' ;;
    30) _inputversion && DEVERSION="${inputversion}"  ;;
    * | "") DEVERSION=1.3.15 ;;
esac

[[ ` echo $DEVERSION | grep -oP "[0-9.]+" | awk -F '.' '{print $3}' ` -lt 11 ]] && DESSL=Yes
[[ $DEVERSION == '1.3.15 (Skip hash check)' ]] && DESKIP=Yes

echo "${bold}${baiqingse}Deluge ${DEVERSION}${normal} ${bold}will be installed${normal}"

echo ; }



# install qbittorrent question (8.8)
function _askqb() {
echo -e "${green}01)${normal} qBittorrent ${green}3.3.7${normal}"
echo -e "${green}02)${normal} qBittorrent ${green}3.3.11${normal}"
echo -e "${green}03)${normal} qBittorrent ${green}3.3.14${normal}"
echo -e "${green}04)${normal} qBittorrent ${green}3.3.16${normal}"
echo -e "${green}11)${normal} qBittorrent ${green}4.0.2${normal}"
echo -e "${green}12)${normal} qBittorrent ${green}4.0.3${normal}"
echo -e "${green}13)${normal} qBittorrent ${green}4.0.4${normal}"
echo -e "${green}14)${normal} qBittorrent ${green}4.1.0${normal}"
echo -e "${green}21)${normal} qBittorrent ${green}3.3.11 (Skip hash check)${normal}"
echo -e "${green}30)${normal} Select another version"
echo -ne "${bold}${yellow}Which version of qBittorrent do you want?${normal} (Default ${green}02${normal}): " ; read -e version

case $version in
    01 | 1) QBVERSION=3.3.7 ;;
    02 | 2) QBVERSION=3.3.11 ;;
    03 | 3) QBVERSION=3.3.14 ;;
    04 | 4) QBVERSION=3.3.16 ;;
    11) QBVERSION=4.0.2 ;;
    12) QBVERSION=4.0.3 ;;
    13) QBVERSION=4.0.4 ;;
    14) QBVERSION=4.1.0 ;;
    21) QBVERSION='3.3.11 (Skip hash check)' ;;
    30) _inputversion && QBVERSION="${inputversion}"  ;;
    * | "") QBVERSION=3.3.11 ;;
esac

echo "${bold}${baiqingse}qBittorrent ${QBVERSION}${normal} ${bold}will be installed${normal}" ; echo ; }




# install transmission question (8.5)
function _asktr() {
  echo -ne "${bold}${yellow}Would you like to install transmission? ${normal} [${green}y${normal}]es or [n]o: "; read responce
  case $responce in
    [yY] | [yY][Ee][Ss] | "" ) tr=yes ;;
    [nN] | [nN][Oo]) tr=no ;;
    *) tr=yes ;;
  esac
  if [[ $tr == yes ]]; then echo "${bold}${baiqingse}Transmission $TR_repo_ver${normal} ${bold}will be installed from repository${normal}"
  else echo "${baizise}Transmission will ${baihongse}not${baizise} be installed${normal}" ; fi
  echo
}


# adduser function (9)
function _adduser() {
  theshell="/bin/bash";
  echo "${bold}${yellow}Add a Master Account user to sudoers${normal}";
  echo -n "Username: "; read user
  username=$(echo "$user"|sed 's/.*/\L&/')
  useradd "${username}" -m -G www-data -s "${theshell}"
  echo -n "Password: (hit enter to generate a password) "; read -e 'password'
  if [[ ! -z "${password}" ]]; then
    echo "setting password to ${password}"
    passwd=${password}
    echo "${username}:${passwd}" | chpasswd >>"${OUTTO}" 2>&1
    (echo -n "${username}:${REALM}:" && echo -n "${username}:${REALM}:${passwd}" | md5sum | awk '{print $1}' ) >> "${HTPASSWD}"
  else
    echo "setting password to ${genpass}"
    passwd=${genpass}
    echo "${username}:${passwd}" | chpasswd >>"${OUTTO}" 2>&1
    (echo -n "${username}:${REALM}:" && echo -n "${username}:${REALM}:${passwd}" | md5sum | awk '{print $1}' ) >> "${HTPASSWD}"
  fi
  printf "${username}:${passwd}" > /root/"$username".info.db
  echo
  ha1pass=`echo -n "${passwd}"|md5sum |cut -f1 -d' '`
}


# ask user for pure-ftpd conf (10.5)
function _askvsftpd() {
  local DEFAULTIP=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1');
  echo -ne "${bold}${yellow}Please, write your public server IP (used for ftp)${normal} (Default: ${green}${bold}$DEFAULTIP${normal}) "; read input
  if [[ -z "$input" ]]; then
    IP=$DEFAULTIP
  else
    IP=$input
  fi
  
  echo
}

# ban public trackers [iptables option] (11)
function _denyhosts() {
  echo -ne "${bold}${yellow}Block Public Trackers?${normal}: [y]es or [${green}n${normal}]o: "; read responce
  case $responce in
    [yY] | [yY][Ee][Ss])

  echo "[ ${red}-  Blocking public trackers  -${normal} ]"
  cp ${local_setup}templates/trackers.template /etc/trackers
  cp ${local_setup}templates/denypublic.template /etc/cron.daily/denypublic
  chmod +x /etc/cron.daily/denypublic
  cat ${local_setup}templates/hostsTrackers.template >> /etc/hosts
    ;;

    [nN] | [nN][Oo] | "") echo "[ ${green}+  Allowing public trackers  +${normal} ]"
    ;;
  esac
  echo
}




# install flexget question (x)
function _askfg() {
  echo -ne "${bold}${yellow}Would you like to install flexget? ${normal} [${green}y${normal}]es or [n]o: "; read responce
  case $responce in
    [yY] | [yY][Ee][Ss] | "" ) fg=yes ;;
    [nN] | [nN][Oo]) fg=no ;;
    *) fg=yes ;;
  esac
  echo
}




# install bbr question (x)
function _askbbr() {
  echo -ne "${bold}${yellow}Would you like to install bbr? (Used for Congestion Control)${normal} [${green}y${normal}]es or [n]o: "; read responce
  case $responce in
    [yY] | [yY][Ee][Ss] | "" ) bbr=yes ;;
    [nN] | [nN][Oo]) bbr=no ;;
    *) bbr=yes ;;
  esac
  echo
}

# package and repo addition (silently add php7) _add respo sources_ (12)
function _repos() {
  apt-get install -y software-properties-common >>"${OUTTO}" 2>&1
  apt-get -y install lsb-release sudo >>"${OUTTO}" 2>&1
  if [[ $DISTRO == Ubuntu ]]; then
    LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php -y >>"${OUTTO}" 2>&1;
  fi

  if [[ $DISTRO == Debian ]]; then
    echo "deb http://packages.dotdeb.org $(lsb_release -sc) all" > /etc/apt/sources.list.d/dotdeb-php7-$(lsb_release -sc).list
    echo "deb-src http://packages.dotdeb.org $(lsb_release -sc) all" >> /etc/apt/sources.list.d/dotdeb-php7-$(lsb_release -sc).list
    wget -q https://www.dotdeb.org/dotdeb.gpg
    sudo apt-key add dotdeb.gpg >> /dev/null 2>&1
  fi

}

# package and repo addition (13) _update and upgrade_
function _updates() {
  if [[ $DISTRO == Debian ]]; then
    cp ${local_setup}templates/apt.sources/debian.template /etc/apt/sources.list
    sed -i "s/RELEASE/${CODENAME}/g" /etc/apt/sources.list
    apt-get --yes --force-yes update >>"${OUTTO}" 2>&1
    yes '' | apt-get install --force-yes build-essential debian-archive-keyring \
                             python-software-properties >>"${OUTTO}" 2>&1
    apt-get --yes --force-yes install deb-multimedia-keyring >>"${OUTTO}" 2>&1
  else
    cp ${local_setup}templates/apt.sources/ubuntu.template /etc/apt/sources.list
    sed -i "s/RELEASE/${CODENAME}/g" /etc/apt/sources.list
    apt-get -y update >>"${OUTTO}" 2>&1
    apt-get -y -f install build-essential debian-archive-keyring \
                             python-software-properties >>"${OUTTO}" 2>&1
    #apt-get -y -f --allow-unauthenticated install deb-multimedia-keyring >>"${OUTTO}" 2>&1
  fi

  if [[ $DISTRO == Debian ]]; then
    export DEBIAN_FRONTEND=noninteractive
    yes '' | apt-get update >>"${OUTTO}" 2>&1
    apt-get -y purge samba samba-common >>"${OUTTO}" 2>&1
    yes '' | apt-get upgrade >>"${OUTTO}" 2>&1
  else
    export DEBIAN_FRONTEND=noninteractive
    apt-get -y update >>"${OUTTO}" 2>&1
    apt-get -y purge samba samba-common >>"${OUTTO}" 2>&1
    apt-get -y upgrade >>"${OUTTO}" 2>&1
  fi

  if [[ -e /etc/ssh/sshd_config ]]; then
    #sed -i 's/SendEnv LANG LC_*/#SendEnv LANG LC_*/g' /etc/ssh/ssh_config
    #sed -i 's/AcceptEnv LANG LC_*/#AcceptEnv LANG LC_*/g' /etc/ssh/sshd_config
    service ssh restart >>"${OUTTO}" 2>&1
  fi

  # Create the service lock file directory
  if [[ -d /install ]]; then cd /; else mkdir /install; fi
  if [[ -d /root/tmp ]]; then cd && rm -r tmp; fi

}

# package and repo addition (14) _install softwares and packages_
function _depends() {
  if [[ $DISTRO == Debian ]]; then
    yes '' | apt-get install --force-yes fail2ban bc ed sudo screen zip irssi unzip nano bwm-ng htop nethogs speedtest.cli iotop \
                     dos2unix subversion dstat automake make mktorrent libtool libcppunit-dev libssl-dev \
                     pkg-config libxml2-dev libcurl3 libcurl4-openssl-dev libsigc++-2.0-dev \
                     apache2-utils autoconf cron curl libapache2-mod-fastcgi libapache2-mod-geoip \
                     libxslt-dev libncurses5-dev yasm pcregrep apache2 php-net-socket libapache2-mod-php7.0 \
                     php7.0-dev php7.0-geoip libgeoip-dev php7.0 php7.0-fpm php7.0-mbstring php7.0-mysql \
                     php7.0-curl php7.0-memcached memcached php7.0-gd php7.0-json php7.0-mcrypt php7.0-opcache \
                     php7.0-xml python3-lxml python-lxml fontconfig comerr-dev ca-certificates libfontconfig1-dev \
                     libdbd-mysql-perl libdbi-perl libfontconfig1 rar unrar mediainfo ifstat \
                     ttf-mscorefonts-installer checkinstall dtach cfv libarchive-zip-perl \
                     libnet-ssleay-perl ca-certificates-java libxslt1-dev \
                     libxslt1.1 libxml2 libffi-dev python-pip python-dev libhtml-parser-perl libxml-libxml-perl \
                     libjson-perl libjson-xs-perl libxml-libxslt-perl libapache2-mod-scgi \
                     vnstat vnstati openvpn >>"${OUTTO}" 2>&1
  elif [[ $DISTRO == Ubuntu ]]; then
    apt-get -y -f --allow-unauthenticated install build-essential debian-archive-keyring fail2ban bc sudo \
                     screen zip irssi unzip nano bwm-ng htop iotop git \
                     dos2unix subversion dstat automake make mktorrent libtool libcppunit-dev libssl-dev \
                     pkg-config libxml2-dev libcurl3 libcurl4-openssl-dev libsigc++-2.0-dev \
                     apache2-utils autoconf cron curl libapache2-mod-fastcgi libapache2-mod-geoip \
                     libxslt-dev libncurses5-dev yasm pcregrep apache2 php-net-socket \
                     libdbd-mysql-perl libdbi-perl php7.0 php7.0-fpm php7.0-mbstring php7.0-mysql \
                     php7.0-curl php-memcached memcached php7.0-gd php7.0-json php7.0-mcrypt php7.0-opcache \
                     php7.0-xml php7.0-zip fontconfig comerr-dev ca-certificates libfontconfig1-dev \
                     php7.0-geoip libfontconfig1 rar unrar mediainfo ifstat libapache2-mod-php7.0 \
                     python3-lxml python-lxml ttf-mscorefonts-installer checkinstall dtach cfv libarchive-zip-perl \
                     libnet-ssleay-perl openjdk-8-jre-headless openjdk-8-jre openjdk-8-jdk libxslt1-dev \
                     libxslt1.1 libxml2 libffi-dev python-pip python-dev libhtml-parser-perl libxml-libxml-perl \
                     libjson-perl libjson-xs-perl libxml-libxslt-perl libapache2-mod-scgi \
                     vnstat vnstati openvpn >>"${OUTTO}" 2>&1
  fi
}

# build openssl from source to combat recent apt source updates
function _openssl() {
  MAXCPUS=$(echo "$(nproc) / 2"|bc)
  cd /root
  wget -q https://www.openssl.org/source/openssl-1.0.2l.tar.gz
  tar -zxvf openssl-1.0.2l.tar.gz >>"${OUTTO}" 2>&1
  cd openssl-1.0.2l
  ./config -fPIC >>"${OUTTO}" 2>&1;
  make -j${MAXCPUS} >>"${OUTTO}" 2>&1;
  #make install >>"${OUTTO}" 2>&1;
  cd /root
  rm -rf openssl-1.0.2l.tar.gz
  cd
}

function _syscommands() {
  mkdir -p /usr/local/bin/quickbox
  cp -r ${local_packages}/. /usr/local/bin/quickbox
  dos2unix $(find /usr/local/bin/quickbox -type f) >>"${OUTTO}" 2>&1;
  chmod +x $(find /usr/local/bin/quickbox -type f) >>"${OUTTO}" 2>&1;
  cp /usr/local/bin/quickbox/system/reload /usr/bin/reload
}

function _skel() {
  if [[ -d /etc/skel ]]; then rm -r /etc/skel;fi
  mkdir /etc/skel
  cp -r ${local_setup}templates/skel/. /etc/skel
  tar xzf ${local_setup}sources/rarlinux-x64-5.3.0.tar.gz -C ./
  cp ./rar/*rar /usr/bin
  cp ./rar/*rar /usr/sbin
  rm -rf rarlinux*.tar.gz
  rm -rf ./rar
  wget -q http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
  gunzip GeoLiteCity.dat.gz>>"${OUTTO}" 2>&1
  mkdir -p /usr/share/GeoIP>>"${OUTTO}" 2>&1
  rm -rf GeoLiteCity.dat.gz
  mv GeoLiteCity.dat /usr/share/GeoIP/GeoIPCity.dat>>"${OUTTO}" 2>&1
  (echo y;echo o conf prerequisites_policy follow;echo o conf commit)>/dev/null 2>&1|cpan Digest::SHA1 >>"${OUTTO}" 2>&1
  (echo y;echo o conf prerequisites_policy follow;echo o conf commit)>/dev/null 2>&1|cpan Digest::SHA >>"${OUTTO}" 2>&1
  mkdir -p /etc/skel/.config/deluge/plugins/
  cd /etc/skel/.config/deluge/
  svn co https://github.com/Aniverse/inexistence/trunk/00.Installation/template/config/deluge/plugins >>"${OUTTO}" 2>&1
}

function _qmount() {
  # Setup mount points for Quotas
  if [[ $quota == yes ]]; then
    if [[ $DISTRO == Ubuntu ]]; then
      if [[ ${primaryroot} == "root" ]]; then
        sed -ie '/\/ / s/defaults/usrjquota=aquota.user,jqfmt=vfsv1,defaults/' /etc/fstab
        sed -i 's/errors=remount-ro/usrjquota=aquota.user,jqfmt=vfsv1,errors=remount-ro/g' /etc/fstab
        apt-get install -y linux-image-extra-virtual quota >>"${OUTTO}" 2>&1
        mount -o remount / || mount -o remount /home >>"${OUTTO}" 2>&1
        quotacheck -auMF vfsv1 >>"${OUTTO}" 2>&1
        quotaon -uv / >>"${OUTTO}" 2>&1
        service quota start >>"${OUTTO}" 2>&1
      else
        sed -ie '/\/home/ s/defaults/usrjquota=aquota.user,jqfmt=vfsv1,defaults/' /etc/fstab
        sed -i 's/errors=remount-ro/usrjquota=aquota.user,jqfmt=vfsv1,errors=remount-ro/g' /etc/fstab
        apt-get install -y linux-image-extra-virtual quota >>"${OUTTO}" 2>&1
        mount -o remount /home >>"${OUTTO}" 2>&1
        quotacheck -auMF vfsv1 >>"${OUTTO}" 2>&1
        quotaon -uv /home >>"${OUTTO}" 2>&1
        service quota start >>"${OUTTO}" 2>&1
      fi
    elif [[ $DISTRO == Debian ]]; then
      if [[ ${primaryroot} == "root" ]]; then
        sed -ie '/\/ / s/defaults/usrjquota=aquota.user,jqfmt=vfsv1,defaults/' /etc/fstab
        sed -i 's/errors=remount-ro/usrjquota=aquota.user,jqfmt=vfsv1,errors=remount-ro/g' /etc/fstab
        apt-get install -y quota >>"${OUTTO}" 2>&1
        mount -o remount / || mount -o remount /home >>"${OUTTO}" 2>&1
        quotacheck -auMF vfsv1 >>"${OUTTO}" 2>&1
        quotaon -uv / >>"${OUTTO}" 2>&1
        service quota start >>"${OUTTO}" 2>&1
      else
        sed -ie '/\/home/ s/defaults/usrjquota=aquota.user,jqfmt=vfsv1,defaults/' /etc/fstab
        sed -i 's/errors=remount-ro/usrjquota=aquota.user,jqfmt=vfsv1,errors=remount-ro/g' /etc/fstab
        apt-get install -y quota >>"${OUTTO}" 2>&1
        mount -o remount /home >>"${OUTTO}" 2>&1
        quotacheck -auMF vfsv1 >>"${OUTTO}" 2>&1
        quotaon -uv /home >>"${OUTTO}" 2>&1
        service quota start >>"${OUTTO}" 2>&1
      fi
    fi
    touch /install/.quota.lock
  fi
}

function _lshell() {
# Setup LShell configuration file
  apt-get -y install lshell >> /dev/null 2>&1
  cp ${local_setup}templates/lshell.conf.template /etc/lshell.conf
}


# build function for ffmpeg (17)
function _ffmpeg() {
cd ; wget --no-check-certificate -O ffmpeg-3.4.2-64bit-static.tar.xz https://github.com/Aniverse/BitTorrentClientCollection/raw/master/Other%20Tools/ffmpeg-3.4.2-64bit-static.tar.xz >>"${OUTTO}" 2>&1
tar xf ffmpeg-3.4.2-64bit-static.tar.xz
rm -rf ffmpeg-*-64bit-static/{manpages,GPLv3.txt,readme.txt}
cp -f ffmpeg-*-64bit-static/* /usr/bin
chmod 777 /usr/bin/{ffmpeg,ffprobe,ffmpeg-10bit,qt-faststart}
rm -rf ffmpeg-*-64bit-static* ; }


# function to enable sudo for www-data function (18)
function _apachesudo() {
  rm /etc/sudoers
  cp ${local_setup}templates/sudoers.template /etc/sudoers
  #if [[ $sudoers == "yes" ]]; then
    awk -v username=${username} '/^root/ && !x {print username    " ALL=(ALL:ALL) NOPASSWD: ALL"; x=1} 1' /etc/sudoers > /tmp/sudoers;mv /tmp/sudoers /etc
    echo -n "${username}" > /etc/apache2/master.txt
  #fi
  cd
}

# xmlrpc-c function (19)
function _xmlrpc() {
  if [[ -d /root/tmp ]]; then rm -r tmp;fi
  mkdir /root/tmp && cd /root/tmp
  if [[ -d /root/tmp/xmlrpc-c ]]; then rm -rf xmlrpc-c;fi
  cp -r ${local_setup}sources/xmlrpc-c_1-33-12/ .
  cd xmlrpc-c_1-33-12
  chmod +x configure
  ./configure --prefix=/usr --disable-cplusplus >>"${OUTTO}" 2>&1
  make >>"${OUTTO}" 2>&1
  chmod +x install-sh
  make install >>"${OUTTO}" 2>&1
}

# libtorrent function (20)
# modify by EFS thanks to asuna's patch
# apt rtorrent handles the libtorrent install
# remember this is temporary until patched
function _libtorrent() {
  if [[ -d /root/tmp ]]; then rm -r tmp;fi
  mkdir /root/tmp && cd /root/tmp
  MAXCPUS=$(echo "$(nproc) / 2"|bc)
  rm -rf xmlrpc-c  >>"${OUTTO}" 2>&1
  if [[ -e /root/tmp/libtorrent-${LTORRENT}.tar.gz ]]; then rm -rf libtorrent-${LTORRENT}.tar.gz;fi
  cp ${local_setup}sources/libtorrent-${LTORRENT}.tar.gz .
  tar -xzvf libtorrent-${LTORRENT}.tar.gz >>"${OUTTO}" 2>&1
  cd libtorrent-${LTORRENT}
  ./autogen.sh >>"${OUTTO}" 2>&1
  if [ $LTORRENT = 0.13.4 ]; then
  cp ${local_setup}sources/libtorrent-0.13.4-tar.patch .
  patch -p1 < libtorrent-*-tar.patch >>"${OUTTO}" 2>&1
  ./configure --prefix=/usr OPENSSL_LIBS="-L/root/openssl-1.0.2l -lssl -lcrypto" OPENSSL_CFLAGS="-I/root/openssl-1.0.2l/include" --enable-ipv6 >>"${OUTTO}" 2>&1
  elif [ $LTORRENT = 0.13.6 ]; then
  ./configure --prefix=/usr OPENSSL_LIBS="-L/root/openssl-1.0.2l -lssl -lcrypto" OPENSSL_CFLAGS="-I/root/openssl-1.0.2l/include" --enable-ipv6 >>"${OUTTO}" 2>&1
  else
  ./configure --prefix=/usr OPENSSL_LIBS="-L/root/openssl-1.0.2l -lssl -lcrypto" OPENSSL_CFLAGS="-I/root/openssl-1.0.2l/include" >>"${OUTTO}" 2>&1
  fi
  make -j${MAXCPUS} >>"${OUTTO}" 2>&1
  make install >>"${OUTTO}" 2>&1
}

# rtorrent function (21)
# commenting until patch comes for comp/build 
# using apt install rtorrent in the meantime
function _rtorrent() {
  if [[ -d /root/tmp ]]; then rm -r tmp;fi
  mkdir /root/tmp && cd /root/tmp
  MAXCPUS=$(echo "$(nproc) / 2"|bc)
  rm -rf libtorrent-${LTORRENT}* >>"${OUTTO}" 2>&1
  if [[ -e /root/tmp/libtorrent-${LTORRENT}.tar.gz ]]; then rm -rf libtorrent-${LTORRENT}.tar.gz;fi
  cp ${local_setup}sources/rtorrent-${RTVERSION}.tar.gz .
  tar -xzvf rtorrent-${RTVERSION}.tar.gz >>"${OUTTO}" 2>&1
  cd rtorrent-${RTVERSION}
  ./autogen.sh >>"${OUTTO}" 2>&1
  if [ $RTVERSION = 0.9.4 ]; then
  cp ${local_setup}sources/rtorrent-0.9.4-tar.patch .
  patch -p1 < rtorrent-*-tar.patch >>"${OUTTO}" 2>&1
  ./configure --prefix=/usr --with-xmlrpc-c --enable-ipv6 >>"${OUTTO}" 2>&1
  elif [ $RTVERSION = 0.9.6 ]; then
  ./configure --prefix=/usr --with-xmlrpc-c --enable-ipv6 >>"${OUTTO}" 2>&1
  else
  ./configure --prefix=/usr --with-xmlrpc-c >>"${OUTTO}" 2>&1
  fi
  make -j${MAXCPUS} >>"${OUTTO}" 2>&1
  make install >>"${OUTTO}" 2>&1
  cd /root/tmp
  ldconfig >>"${OUTTO}" 2>&1
  rm -rf /root/tmp/rtorrent-${RTVERSION}* >>"${OUTTO}" 2>&1
  touch /install/.rtorrent.lock
}
function _rtorrent_fallback() {
  apt-get install -y rtorrent >>"${OUTTO}" 2>&1
  touch /install/.rtorrent.lock
}

function _boost() {
  cd /tmp
  wget -O boost_1_65_1.tar.gz -q https://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.gz/download
  tar -zxvf boost_1_65_1.tar.gz >>"${OUTTO}" 2>&1
  cd boost_1_65_1
  ./bootstrap.sh --prefix=/usr/ --with-libraries=system --with-libraries=python --with-libraries=chrono --with-libraries=random >>"${OUTTO}" 2>&1;
  ./b2 >>"${OUTTO}" 2>&1;
  ./b2 install >>"${OUTTO}" 2>&1;
  cd /tmp
  rm -rf boost_1_65_1.tar.gz boost_1_65_1
  cd
}



# 使用 deb 包安装 libtorrent-rasterbar
function _install_lt_deb_1011() {

apt-get install -y                                                                  \
build-essential pkg-config autoconf automake libtool git checkinstall               \
libboost-dev libboost-system-dev libboost-chrono-dev libboost-random-dev libssl-dev \
geoip-database libgeoip-dev                                                         \
libboost-python-dev                                                                 \
zlib1g-dev

if [[ $CODENAME == jessie ]]; then
    wget --no-check-certificate https://github.com/Aniverse/BitTorrentClientCollection/raw/master/Deb%20Package/Jessie/libtorrent-rasterbar_1.0.11_jessie_amd64.deb -qO lt.deb
elif [[ $CODENAME == xenial ]]; then
    wget --no-check-certificate https://github.com/Aniverse/BitTorrentClientCollection/raw/master/Deb%20Package/Xenial/libtorrent-rasterbar_1.0.11_xenial_amd64.deb -qO lt.deb
elif [[ $CODENAME == stretch ]]; then
    wget --no-check-certificate https://github.com/Aniverse/BitTorrentClientCollection/raw/master/Deb%20Package/Stretch/libtorrent-rasterbar_1.0.11_stretch_amd64.deb -qO lt.deb
fi

dpkg -i lt.deb && rm -rf lt.deb
ldconfig ; }




# 安装 Deluge
function _deluge() { cd

_install_lt_deb_1011 >>"${OUTTO}" 2>&1;
apt-get install -y python python-twisted python-openssl python-setuptools intltool python-xdg python-chardet geoip-database python-notify python-pygame python-glade2 librsvg2-common xdg-utils python-mako >>"${OUTTO}" 2>&1

if [[ $DESKIP == Yes ]]; then
    export DEVERSION=1.3.15
    wget --no-check-certificate -O deluge-$DEVERSION.tar.gz https://github.com/Aniverse/BitTorrentClientCollection/raw/master/Deluge/deluge-$DEVERSION.skip.tar.gz  >>"${OUTTO}" 2>&1
else
    wget --no-check-certificate http://download.deluge-torrent.org/source/deluge-$DEVERSION.tar.gz  >>"${OUTTO}" 2>&1
fi

tar xf deluge-$DEVERSION.tar.gz
rm -f deluge-$DEVERSION.tar.gz
cd deluge-$DEVERSION

if [[ $DESSL == Yes ]]; then
    sed -i "s/SSL.SSLv3_METHOD/SSL.SSLv23_METHOD/g" deluge/core/rpcserver.py
    sed -i "/    ctx = SSL.Context(SSL.SSLv23_METHOD)/a\    ctx.set_options(SSL.OP_NO_SSLv2 & SSL.OP_NO_SSLv3)" deluge/core/rpcserver.py
    python setup.py build  >>"${OUTTO}" 2>&1
    python setup.py install --install-layout=deb  >>"${OUTTO}" 2>&1
    mv -f /usr/bin/deluged /usr/bin/deluged2
    wget --no-check-certificate http://download.deluge-torrent.org/source/deluge-1.3.15.tar.gz >>"${OUTTO}" 2>&1
    tar xf deluge-1.3.15.tar.gz && rm -f deluge-1.3.15.tar.gz && cd deluge-1.3.15
fi

python setup.py build   >>"${OUTTO}" 2>&1
python setup.py install --install-layout=deb  >>"${OUTTO}" 2>&1
python setup.py install_data  >>"${OUTTO}" 2>&1
cd ; rm -rf deluge-$DEVERSION

[[ $DESSL == Yes ]] && mv -f /usr/bin/deluged2 /usr/bin/deluged # 让老版本 Deluged 保留，其他用新版本

n=$RANDOM
DPORT=$((n%59000+10024))
DWSALT=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
DWP=$(python ${local_packages}/system/deluge.Userpass.py ${passwd} ${DWSALT})
DUDID=$(python ${local_packages}/system/deluge.addHost.py)
DWPORT=$(shuf -i 10001-11000 -n 1)
mkdir -p /home/${username}/.config/deluge
cd /home/${username}/.config/deluge
svn co https://github.com/Aniverse/inexistence/trunk/00.Installation/template/config/deluge/plugins >>"${OUTTO}" 2>&1
chmod 755 /home/${username}/.config
chmod 755 /home/${username}/.config/deluge
cp ${local_setup}templates/core.conf.template /home/${username}/.config/deluge/core.conf
cp ${local_setup}templates/web.conf.template /home/${username}/.config/deluge/web.conf
cp ${local_setup}templates/hostlist.conf.1.2.template /home/${username}/.config/deluge/hostlist.conf.1.2
cp ${local_setup}templates/ltconfig.conf.template /home/${username}/.config/deluge/ltconfig.conf
sed -i "s/USERNAME/${username}/g" /home/${username}/.config/deluge/core.conf
sed -i "s/DPORT/${DPORT}/g" /home/${username}/.config/deluge/core.conf
sed -i "s/DWPORT/${DWPORT}/g" /home/${username}/.config/deluge/web.conf
sed -i "s/DWSALT/${DWSALT}/g" /home/${username}/.config/deluge/web.conf
sed -i "s/DWP/${DWP}/g" /home/${username}/.config/deluge/web.conf
sed -i "s/DUDID/${DUDID}/g" /home/${username}/.config/deluge/hostlist.conf.1.2
sed -i "s/DPORT/${DPORT}/g" /home/${username}/.config/deluge/hostlist.conf.1.2
sed -i "s/USERNAME/${username}/g" /home/${username}/.config/deluge/hostlist.conf.1.2
sed -i "s/PASSWD/${passwd}/g" /home/${username}/.config/deluge/hostlist.conf.1.2
echo "${username}:${passwd}:10" > /home/${username}/.config/deluge/auth
chmod 600 /home/${username}/.config/deluge/auth
chown -R ${username}.${username} /home/${username}/.config/
mkdir /home/${username}/dwatch
chown ${username}: /home/${username}/dwatch
mkdir -p /home/${username}/torrents/deluge
chown ${username}: /home/${username}/torrents/deluge
}







function _insdwApache() {
APPNAME='deluge'
APPDPORT=`cat /home/${username}/.config/deluge/web.conf | grep -E ".*port.*" | grep -Eo [0-9]+`
  cat > /etc/apache2/sites-enabled/deluge.conf <<EOF
ProxyPass /$APPNAME http://localhost:$APPDPORT/

<Location /$APPNAME>
    ProxyPassReverse /
    ProxyPassReverseCookiePath / /$APPNAME              
    RequestHeader set X-Deluge-Base "/$APPNAME/"          
    Order allow,deny
    Allow from all
</Location>
EOF

  touch /install/.deluge.lock
  chown www-data: /etc/apache2/sites-enabled/deluge.conf
}

function _insTr() {
  apt-get -q -y update >>"${OUTTO}" 2>&1
  apt-get -q -y install transmission-daemon >>"${OUTTO}" 2>&1
  service transmission-daemon stop >>"${OUTTO}" 2>&1
  mkdir -p /home/${username}/torrents/transmission
  chmod g+w /home/${username}/torrents/transmission >/dev/null 2>&1
  usermod -a -G debian-transmission ${username} >/dev/null 2>&1
  #chgrp -R debian-transmission /home/${username}/torrents/transmission
  chown -R ${username}:debian-transmission /home/${username}/torrents/transmission >/dev/null 2>&1
  sed -i "s/\/var\/lib\/transmission-daemon\/downloads/\/home\/${username}\/torrents\/transmission/g" /etc/transmission-daemon/settings.json
  sed -i "s/\/var\/lib\/transmission-daemon\/Downloads/\/home\/${username}\/torrents\/transmission\/incomplete/g" /etc/transmission-daemon/settings.json
  sed -i "s/\"{.*/\"${passwd}\", /g" /etc/transmission-daemon/settings.json
  sed -i "s/\"transmission\",/\"${username}\",/g" /etc/transmission-daemon/settings.json
  sed -i "s/127.0.0.1/\*.\*.\*.\*/g" /etc/transmission-daemon/settings.json
  service transmission-daemon start >>"${OUTTO}" 2>&1
}

function _insTrWeb() {
  #!/bin/sh
  # 获取第一个参数做为目录
  ROOT_FOLDER="$1"
  WEB_FOLDER=""
  ORG_INDEX_FILE="index.original.html"
  INDEX_FILE="index.html"
  TMP_FOLDER="/tmp/tr-web-control"
  PACK_NAME="src.tar.gz"
	WEB_HOST="https://github.com/ronggang/twc-release/raw/master/"
	DOWNLOAD_URL="$WEB_HOST$PACK_NAME"
	# 安装类型
	# 1 安装至当前 Transmission Web 所在目录
	# 2 安装至 TRANSMISSION_WEB_HOME 环境变量指定的目录，参考：https://github.com/transmission/transmission/wiki/Environment-Variables#transmission-specific-variables
	# 使用环境变量时，如果 transmission 不是当前用户运行的，则需要将 TRANSMISSION_WEB_HOME 添加至 /etc/profile 文件，以达到“永久”的目的
	# 3 用户指定参数做为目录，如 sh install-tr-control.sh /usr/local/transmission/share/transmission
	INSTALL_TYPE=-1

	# 开始
	main() {
	  # 判断临时目录是否存在，不存在则创建
	  if [ ! -d "$TMP_FOLDER" ]; then
		mkdir -p "$TMP_FOLDER"
	  fi

	  # 判断 ROOT_FOLDER 是否为一个有效的目录，如果是则表明传递了一个有效路径
	  if [ -d "$ROOT_FOLDER" ]; then
		echo "use arg: $ROOT_FOLDER" >>"${OUTTO}" 2>&1
		INSTALL_TYPE=3
		WEB_FOLDER="$ROOT_FOLDER/web"
	  else
		# 查找目录
		findWebFolder
	  fi
	  # 安装
	  install
	  # 清理
	  clear
	}

	# 查找Web目录
	findWebFolder() {
	  # 找出web ui 目录
	  echo "Searching Transmission Web Folder..."  >>"${OUTTO}" 2>&1
	  # 指定一次当前系统的默认目录
	  # 用户如知道自己的 Transmission Web 所在的目录，直接修改这个值，以避免搜索所有目录
	  ROOT_FOLDER="/usr/local/transmission/share/transmission"
	  # Fedora 或 Debian 发行版的默认 ROOT_FOLDER 目录
	  if [ -f /etc/fedora-release ] || [ -f "/etc/debian_version" ]; then
		ROOT_FOLDER="/usr/share/transmission"
	  fi
		
	  # 判断 TRANSMISSION_WEB_HOME 环境变量是否被定义，如果是，直接用这个变量的值
	  if [ $TRANSMISSION_WEB_HOME ]; then
		echo "use TRANSMISSION_WEB_HOME: $TRANSMISSION_WEB_HOME" >>"${OUTTO}" 2>&1
		# 判断目录是否存在，如果不存在则创建 https://github.com/ronggang/transmission-web-control/issues/167
		if [ ! -d "$TRANSMISSION_WEB_HOME" ]; then
			 mkdir -p "$TRANSMISSION_WEB_HOME"
		  fi
		INSTALL_TYPE=2
	  else
		echo "Looking for folder: $ROOT_FOLDER/web" >>"${OUTTO}" 2>&1
		if [ -d "$ROOT_FOLDER/web" ]; then
		  WEB_FOLDER="$ROOT_FOLDER/web"
		  INSTALL_TYPE=1
		  echo "Folder found. Using it." >>"${OUTTO}" 2>&1
		else
		  echo "Folder not found. Will search the entire /. This will take a while..." >>"${OUTTO}" 2>&1
		  ROOT_FOLDER=`find / -name 'web' -type d 2>/dev/null| grep 'transmission/web' | sed 's/\/web$//g'`

		  if [ -d "$ROOT_FOLDER/web" ]; then
			WEB_FOLDER="$ROOT_FOLDER/web"
			INSTALL_TYPE=1
		  fi
		fi
	  fi
	}

	# 安装
	install() {
	  # 如果目录存在，则进行下载和更新动作
	  if [ $INSTALL_TYPE = 1 -o $INSTALL_TYPE = 3 ]; then
		# 下载最新的安装包
		download
		echo "Installing..." >>"${OUTTO}" 2>&1
		# 创建web文件夹，从 20171014 之后，打包文件不包含web目录，直接打包为src下所有文件
		mkdir web
		# 解压缩包
		tar -xzf "$PACK_NAME" -C "web" >>"${OUTTO}" 2>&1
		# 如果之前没有安装过，则先将原系统的文件改为
		if [ ! -f "$WEB_FOLDER/$ORG_INDEX_FILE" -a -f "$WEB_FOLDER/$INDEX_FILE" ]; then
		  mv "$WEB_FOLDER/$INDEX_FILE" "$WEB_FOLDER/$ORG_INDEX_FILE"
		fi
		# 复制文件到
		cp -r web "$ROOT_FOLDER"

		# 设置权限
		find "$ROOT_FOLDER" -type d -exec chmod o+rx {} \;
		find "$ROOT_FOLDER" -type f -exec chmod o+r {} \;

		# 安装完成
		installed
	  elif [ $INSTALL_TYPE = 2 ]; then
		# 下载最新的安装包
		download
		echo "Installing..." >>"${OUTTO}" 2>&1
		# 解压缩包
		tar -xzf "$PACK_NAME" -C "$TRANSMISSION_WEB_HOME"

		# 设置权限
		find "$TRANSMISSION_WEB_HOME" -type d -exec chmod o+rx {} \;
		find "$TRANSMISSION_WEB_HOME" -type f -exec chmod o+r {} \;

		# 安装完成
		installed
	  else
			#echo "##############################################"
			#echo "#"
			echo "# ERROR : Transmisson WEB UI Folder is missing." >>"${OUTTO}" 2>&1
			#echo "#"
			#echo "##############################################"
	  fi
	}

	# 下载最新的安装包
	download() {
	  cd "$TMP_FOLDER"
	  echo "Downloading Transmission Web Control..." >>"${OUTTO}" 2>&1
	  wget -q "$DOWNLOAD_URL" --no-check-certificate
	}

	# 安装完成
	installed() {
	  echo "Transmission Web Control Installation completed!" >>"${OUTTO}" 2>&1
	}

	# 清除工作
	clear() {
	  # 删除安装包
	  rm "$PACK_NAME"
	  # 删除临时目录
	  rm -rf "$TMP_FOLDER"
	}

	# 执行
	main

  rm -rf "$tmpFolder"
  #touch /install/.transmission.lock
  #cd ${local_dashboard}/custom
  #patch -p1 < ${local_setup}templates/tr-php.patch >>"${OUTTO}" 2>&1
}

function _insTrApache() {
APPNAME='transmission'
APPDPORT='9091'
  cat > /etc/apache2/sites-enabled/transmission.conf <<EOF
<Location /$APPNAME>
ProxyPass http://localhost:$APPDPORT/$APPNAME
ProxyPassReverse http://localhost:$APPDPORT/$APPNAME
Require all granted
</Location>
EOF

  touch /install/.transmission.lock
  chown www-data: /etc/apache2/sites-enabled/transmission.conf
  cat > /usr/share/transmission/web/.htaccess <<EOF
allow from all
EOF
}


function _qbittorrent() { cd

if [[ $CODENAME == jessie ]]; then
    apt-get install -y libgl1-mesa-dev >>"${OUTTO}" 2>&1
    wget --no-check-certificate -qO qt_5.5.1-1_amd64_debian8.deb https://github.com/Aniverse/BitTorrentClientCollection/raw/master/Other%20Tools/qt_5.5.1-1_amd64_debian8.deb
    dpkg -i qt_5.5.1-1_amd64_debian8.deb >>"${OUTTO}" 2>&1
    rm -f qt_5.5.1-1_amd64_debian8.deb >>"${OUTTO}" 2>&1
    export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/Qt-5.5.1/lib/pkgconfig
    export PATH=/usr/local/Qt-5.5.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
else
    apt-get install -y qtbase5-dev qttools5-dev-tools libqt5svg5-dev >>"${OUTTO}" 2>&1
fi

git clone https://github.com/qbittorrent/qBittorrent >>"${OUTTO}" 2>&1
cd qBittorrent
 [[ $QBVERSION == '3.3.11 (Skip hash check)' ]] && QBVERSION=3.3.11
git checkout release-$QBVERSION >>"${OUTTO}" 2>&1

if [[ $QBPATCH == Yes ]]; then
    git config --global user.email "you@example.com" >>"${OUTTO}" 2>&1
    git config --global user.name "Your Name" >>"${OUTTO}" 2>&1
    git cherry-pick db3158c >>"${OUTTO}" 2>&1
    git cherry-pick b271fa9 >>"${OUTTO}" 2>&1
    git cherry-pick 1ce71fc >>"${OUTTO}" 2>&1
fi

./configure --disable-gui >>"${OUTTO}" 2>&1
make -j$(nproc) >>"${OUTTO}" 2>&1
make install >>"${OUTTO}" 2>&1

# mkdir -p doc-pak
# cat >description-pak<<EOF
# qBittorrent BitTorrent client headless (qbittorrent-nox)
# EOF
# checkinstall -y --pkgname=qbittorrent-headless --pkgversion=$QBVERSION --pkggroup qbittorrent >>"${OUTTO}" 2>&1

cp ${local_setup}templates/sysd/qbittorrent.template /etc/systemd/system/qbittorrent@.service >/dev/null 2>&1
systemctl enable qbittorrent@${username} >/dev/null 2>&1
cd ; sleep 10
mkdir -p /home/${username}/.config/qBittorrent
cp -f ${local_setup}templates/qBittorrent.conf.template /home/${username}/.config/qBittorrent/qBittorrent.conf
sed -i "s/SCRIPTUSERNAME/${username}/g" /home/${username}/.config/qBittorrent/qBittorrent.conf
sed -i "s/SCRIPTQBPASS/${ha1pass}/g" /home/${username}/.config/qBittorrent/qBittorrent.conf
sed -i "s/mySavePath/\/home\/${username}\/torrents\/qbittorrent/g" /home/${username}/.config/qBittorrent/qBittorrent.conf
chmod -R 755 /home/${username}/.config/
chown -R ${username}.${username} /home/${username}/.config/
mkdir -p /home/${username}/torrents/qbittorrent
chown ${username}: /home/${username}/torrents/qbittorrent
cd ${local_packages}
rm -rf qBittorrent
systemctl start qbittorrent@${username} >/dev/null 2>&1
}





function _insqBApache() {
APPNAME='qbittorrent'
APPDPORT='8086'
  cat > /etc/apache2/sites-enabled/qbittorrent.conf <<EOF
<Location /$APPNAME>
ProxyPass http://localhost:$APPDPORT
ProxyPassReverse http://localhost:$APPDPORT
Require all granted
</Location>
EOF

  touch /install/.qbittorrent.lock
  chown www-data: /etc/apache2/sites-enabled/qbittorrent.conf
}




# function to install flexget
function _insfg() {

  apt-get -y install python-pip >>"${OUTTO}" 2>&1
  pip install --upgrade pip setuptools >>"${OUTTO}" 2>&1
  /usr/local/bin/pip install markdown >>"${OUTTO}" 2>&1
  /usr/local/bin/pip install flexget  >>"${OUTTO}" 2>&1
  /usr/local/bin/pip install transmissionrpc >>"${OUTTO}" 2>&1

  mkdir -p /home/${username}/.config/flexget /home/${username}/torrents/{transmission,qbittorrent,rtorrent,deluge}

  touch /home/${username}/cookies.txt
  cp -f ${local_setup}templates/flexget.config.yml.template /home/${username}/.config/flexget/config.yml
  sed -i "s/DWPORT/${DWPORT}/g" /home/${username}/.config/flexget/config.yml
  sed -i "s/SCRIPTUSERNAME/${username}/g" /home/${username}/.config/flexget/config.yml
  sed -i "s/SCRIPTPASSWORD/${passwd}/g" /home/${username}/.config/flexget/config.yml
  chmod -R 755 /home/${username}/.config/flexget /home/${username}/cookies.txt
  chown -R ${username}: /home/${username}/.config/flexget /home/${username}/cookies.txt /home/${username}/torrents/{transmission,qbittorrent,rtorrent,deluge}

  flexget web passwd $passwd  >>"${OUTTO}" 2>&1

  cp -f ${local_setup}templates/sysd/flexget.template /etc/systemd/system/flexget@.service >/dev/null 2>&1
  systemctl daemon-reload
  systemctl enable /etc/systemd/system/flexget@${username}.service >/dev/null 2>&1
  systemctl start flexget@${username} >/dev/null 2>&1
  touch /install/.flexget.lock

}





# scgi enable function (22-nixed)
# function _scgi() { ln -s /etc/apache2/mods-available/scgi.load /etc/apache2/mods-enabled/scgi.load >>"${OUTTO}" 2>&1 ; }

# mktorrent function (xx)
function _mktorrent() {
  if [[ -d /root/tmp ]]; then rm -r tmp;fi
  mkdir /root/tmp && cd /root/tmp
  mktorrent_version=1.1
  wget --quiet https://github.com/Rudde/mktorrent/archive/v$mktorrent_version.zip -O mktorrent.zip  >>"${OUTTO}" 2>&1
  unzip -o mktorrent.zip  >>"${OUTTO}" 2>&1
  cd mktorrent-1.1
  make >>"${OUTTO}" 2>&1
  make install >>"${OUTTO}" 2>&1
  cd ..
  rm -rf mktorrent-1.1 && rm -f mktorrent.zip
}

# function to install rutorrent (22)
function _rutorrent() {
  cd /srv
  if [[ -d /srv/rutorrent ]]; then rm -rf rutorrent;fi
  mkdir rutorrent
  cp -r ${local_rutorrent}/. rutorrent
}

function _rutorrent-plugins() {
  cd /srv/rutorrent
  if [[ -d /srv/rutorrent/plugins ]]; then rm -rf plugins;fi
  mkdir plugins
  cp -R ${local_rplugins}/. plugins
  apt-get install -y sox libsox-fmt-mp3  >>"${OUTTO}" 2>&1
}

# function to install dashboard (23)
function _dashboard() {
  cd && mkdir -p /srv/rutorrent/home
  cp -r ${local_dashboard}. /srv/rutorrent/home
  touch /srv/rutorrent/home/db/output.log
  touch /srv/rutorrent/home/db/.${dash_theme}.lock
  [[ -e /install/.flexget.lock ]] && cp -f ${local_dashboard}custom2/custom.menu.php /srv/rutorrent/home/custom/custom.menu.php
}

# function to install _h5ai file indexer (24x)
function _fileindexer() {
  cd /srv/rutorrent/home
  wget --quiet https://release.larsjung.de/h5ai/h5ai-0.29.0.zip >>"${OUTTO}" 2>&1
  unzip h5ai-0.29.0.zip >>"${OUTTO}" 2>&1
  rm –rf h5ai-0.29.0.zip >>"${OUTTO}" 2>&1
  chmod 775 -R _h5ai/private/cache && chmod 775 -R _h5ai/public/cache
  apt -y install imagemagick >>"${OUTTO}" 2>&1
  echo "DirectoryIndex index.html index.php /_h5ai/public/index.php" >> /etc/apache2/apache2.conf
  [[ ${tr} == "yes" ]] && ln -s /home/${username}/torrents/transmission/ ${username}.transmission.downloads
  ln -s /home/${username}/torrents/rtorrent/ ${username}.rtorrent.downloads
  ln -s /home/${username}/torrents/deluge/ ${username}.deluge.downloads
  ln -s /home/${username}/torrents/qbittorrent/ ${username}.qbittorrent.downloads
}

# function to configure apache (24)
function _apacheconf() {
  cp ${local_setup}templates/aliases-seedbox.conf.template /etc/apache2/sites-enabled/aliases-seedbox.conf
  sed -i "s/USERNAME/${username}/g" /etc/apache2/sites-enabled/aliases-seedbox.conf
  a2enmod auth_digest >>"${OUTTO}" 2>&1
  a2enmod ssl >>"${OUTTO}" 2>&1
  a2enmod scgi >>"${OUTTO}" 2>&1
  a2enmod rewrite >>"${OUTTO}" 2>&1
  mv /etc/apache2/sites-enabled/000-default.conf /etc/apache2/ >>"${OUTTO}" 2>&1
  cp ${local_setup}templates/default-ssl.conf.template /etc/apache2/sites-enabled/default-ssl.conf
  sed -i "s/USERNAME/${username}/g" /etc/apache2/sites-enabled/default-ssl.conf
  sed -i "s/\"REALM\"/\"${REALM}\"/g" /etc/apache2/sites-enabled/default-ssl.conf
  sed -i "s/HTPASSWD/\/etc\/htpasswd/g" /etc/apache2/sites-enabled/default-ssl.conf
  sed -i "s/PORT/${PORT}/g" /etc/apache2/sites-enabled/default-ssl.conf
  sed -i "s/ServerTokens OS/ServerTokens Prod/g" /etc/apache2/conf-enabled/security.conf
  sed -i "s/ServerSignature On/ServerSignature Off/g" /etc/apache2/conf-enabled/security.conf
  cp ${local_setup}templates/fileshare.conf.template /etc/apache2/sites-enabled/fileshare.conf
    sed -i.bak -e "s/post_max_size = 8M/post_max_size = 64M/" \
               -e "s/upload_max_filesize = 2M/upload_max_filesize = 92M/" \
               -e "s/expose_php = On/expose_php = Off/" \
               -e "s/128M/768M/" \
               -e "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/" \
               -e "s/;opcache.enable=0/opcache.enable=1/" \
               -e "s/;opcache.memory_consumption=64/opcache.memory_consumption=128/" \
               -e "s/;opcache.max_accelerated_files=2000/opcache.max_accelerated_files=4000/" \
               -e "s/;opcache.revalidate_freq=2/opcache.revalidate_freq=240/" /etc/php/7.0/fpm/php.ini
    sed -i.bak -e "s/post_max_size = 8M/post_max_size = 64M/" \
               -e "s/upload_max_filesize = 2M/upload_max_filesize = 92M/" \
               -e "s/expose_php = On/expose_php = Off/" \
               -e "s/memory_limit = 128M/memory_limit = 768M/" \
               -e "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/" \
               -e "s/;opcache.enable=0/opcache.enable=1/" \
               -e "s/;opcache.memory_consumption=64/opcache.memory_consumption=128/" \
               -e "s/;opcache.max_accelerated_files=2000/opcache.max_accelerated_files=4000/" \
               -e "s/;opcache.revalidate_freq=2/opcache.revalidate_freq=240/" /etc/php/7.0/apache2/php.ini

    # ensure opcache module is activated
    phpenmod -v 7.0 opcache >>"${OUTTO}" 2>&1

    # these modules are purely experimental
    #a2enmod proxy_fcgi >>"${OUTTO}" 2>&1
    #a2dismod mpm_prefork >>"${OUTTO}" 2>&1
    #a2enmod mpm_worker >>"${OUTTO}" 2>&1

    # ensure fastcgi module is activated
    a2enmod actions >>"${OUTTO}" 2>&1
    a2enmod headers >>"${OUTTO}" 2>&1
    a2enmod fastcgi >>"${OUTTO}" 2>&1
    a2enmod proxy_fcgi setenvif >>"${OUTTO}" 2>&1
    a2enconf php7.0-fpm >>"${OUTTO}" 2>&1


    #sed -i 's/memory_limit = 128M/memory_limit = 768M/g' /etc/php/7.0/apache2/php.ini
}

# function to fix cert (24x)
# add by EFS
function _fix_cert() {
  if [ ! -f /etc/ssl/certs/ssl-cert-snakeoila.pem ]
  then 
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout /etc/ssl/private/ssl-cert-snakeoil.key -out /etc/ssl/certs/ssl-cert-snakeoil.pem -subj "/C=CN/ST=BJ/L=PRC/O=IT/CN=www.example.com" >>"${OUTTO}" 2>&1
  fi
}

# function to configure first user config (25)
function _rconf() {
  cp ${local_setup}templates/rtorrent.rc.template /home/${username}/.rtorrent.rc
  mkdir -p /home/${username}/torrents/rtorrent
  chown -R ${username}: /home/${username}/torrents
  sed -i "s/USERNAME/${username}/g" /home/${username}/.rtorrent.rc
  sed -i "s/XXX/${PORT}/g" /home/${username}/.rtorrent.rc
  sed -i "s/YYY/${PORTEND}/g" /home/${username}/.rtorrent.rc
}

# function to set proper diskspace plugin (26)
function _plugins() {
  cd "${rutorrent}plugins/"
  if [[ ${primaryroot} == "root" ]]; then
    rm -r ${rutorrent}plugins/diskspaceh
  else
    rm -r ${rutorrent}plugins/diskspace
  fi

  cp /srv/rutorrent/home/fileshare/.htaccess /srv/rutorrent/plugins/fileshare/
  cd /srv/rutorrent/home/fileshare/
  rm -rf share.php
  ln -s ../../plugins/fileshare/share.php
  cp ${local_setup}templates/rutorrent/plugins/fileshare/conf.php.template /srv/rutorrent/plugins/fileshare/conf.php

  sed -i 's/homeDirectory/topDirectory/g' /srv/rutorrent/plugins/filemanager/flm.class.php
  sed -i 's/homeDirectory/topDirectory/g' /srv/rutorrent/plugins/filemanager/settings.js.php
  sed -i 's/showhidden: true,/showhidden: false,/g' "${rutorrent}plugins/filemanager/init.js"
  chown -R www-data.www-data "${rutorrent}"
  cd ${rutorrent}plugins/theme/themes/
  git clone https://github.com/QuickBox/club-QuickBox club-QuickBox >>"${OUTTO}" 2>&1
  chown -R www-data:www-data club-QuickBox
  cd ${rutorrent}plugins
  perl -pi -e "s/\$defaultTheme \= \"\"\;/\$defaultTheme \= \"club-QuickBox\"\;/g" ${rutorrent}plugins/theme/conf.php
  rm -rf ${rutorrent}plugins/tracklabels/labels/nlb.png

  # Needed for fileupload
  # wget http://ftp.nl.debian.org/debian/pool/main/p/plowshare/plowshare4_2.1.3-1_all.deb -O plowshare4.deb >>"${OUTTO}" 2>&1
  # wget http://ftp.nl.debian.org/debian/pool/main/p/plowshare/plowshare_2.1.3-1_all.deb -O plowshare.deb >>"${OUTTO}" 2>&1
  apt-get -y install plowshare >>"${OUTTO}" 2>&1
  dpkg -i plowshare*.deb >>"${OUTTO}" 2>&1
  rm -rf plowshare*.deb >>"${OUTTO}" 2>&1
  cd /root
  mkdir -p /root/bin
  git clone https://github.com/mcrapet/plowshare.git ~/.plowshare-source >>"${OUTTO}" 2>&1
  cd ~/.plowshare-source >>"${OUTTO}" 2>&1
  make install PREFIX=$HOME >>"${OUTTO}" 2>&1
  cd && rm -rf .plowshare-source >>"${OUTTO}" 2>&1
  apt-get -f install >>"${OUTTO}" 2>&1

  mkdir -p /srv/rutorrent/conf/users/"${username}"/plugins/fileupload/
  chmod 775 /srv/rutorrent/plugins/fileupload/scripts/upload
  cp /srv/rutorrent/plugins/fileupload/conf.php /srv/rutorrent/conf/users/"${username}"/plugins/fileupload/conf.php
  chown -R www-data: /srv/rutorrent/conf/users/"${username}"

  # Set proper permissions to filemanager so it may execute commands
  find /srv/rutorrent/plugins/filemanager/scripts -type f -exec chmod 755 {} \;
}

# function autodl to install autodl irssi scripts (27)
function _autodl() {
  mkdir -p "/home/${username}/.irssi/scripts/autorun/" >>"${OUTTO}" 2>&1
  cd "/home/${username}/.irssi/scripts/"
  # Grab the most recent version of AutoDL-trackers
  curl -sL http://git.io/vlcND | grep -Po '(?<="browser_download_url": ")(.*-v[\d.]+.zip)' | xargs wget --quiet -O autodl-irssi.zip
  unzip -o autodl-irssi.zip >>"${OUTTO}" 2>&1
  rm autodl-irssi.zip
  cp autodl-irssi.pl autorun/
  mkdir -p "/home/${username}/.autodl" >>"${OUTTO}" 2>&1
  touch "/home/${username}/.autodl/autodl.cfg"
  chown ${username}: /home/${username}/.autodl/autodl.cfg
  touch /install/.autodlirssi.lock

cat >"/home/${username}/.autodl/autodl2.cfg"<<ADC
[options]
gui-server-port = ${AUTODLPORT}
gui-server-password = ${AUTODLPASSWORD}
ADC

  chown -R "${username}.${username}" "/home/${username}/.irssi/"
  chown -R "${username}.${username}" "/home/${username}"
}

# function to make dirs for first user (28)
function _makedirs() {
  #mkdir /home/"${username}"/{torrents,.sessions,watch} >>"${OUTTO}" 2>&1
  cp -r /etc/skel/. /home/"${username}"
  chown -R "${username}".www-data /home/"${username}" >>"${OUTTO}" 2>&1 #/{torrents,.sessions,watch,.rtorrent.rc} >>"${OUTTO}" 2>&1
  usermod -a -G www-data "${username}" >>"${OUTTO}" 2>&1
  usermod -a -G "${username}" www-data >>"${OUTTO}" 2>&1
}

# function to make crontab .statup file (29)
#function _cronfile() {
#  cp ${local_setup}templates/startup.template /home/${username}/.startup
#  chmod 775 /home/${username}/.startup
#  if [[ $DELUGE != NO ]]; then
#  sed -i 's/DELUGEWEB_CLIENT=no/DELUGEWEB_CLIENT=yes/g' /home/${username}/.startup
#  sed -i 's/DELUGED_CLIENT=no/DELUGED_CLIENT=yes/g' /home/${username}/.startup
#fi
#}

# function to configure first user config.php (30)
function _ruconf() {
  mkdir -p ${rutorrent}conf/users/${username}/

  cp ${local_setup}templates/rutorrent.users.config.template ${rutorrent}conf/users/${username}/config.php

  chown -R www-data.www-data "${rutorrent}conf/users/" >>"${OUTTO}" 2>&1
  if [[ ${primaryroot} == "root" ]]; then
    sed -i "/diskuser/c\$diskuser = \"\/\";" /srv/rutorrent/conf/users/${username}/config.php
  else
    sed -i "/diskuser/c\$diskuser = \"\/home\";" /srv/rutorrent/conf/users/${username}/config.php
  fi
  sed -i "/quotaUser/c\$quotaUser = \"${username}\";" /srv/rutorrent/conf/users/${username}/config.php
  sed -i "s/USERNAME/${username}/g" /srv/rutorrent/conf/users/${username}/config.php
  sed -i "s/XXX/${PORT}/g" /srv/rutorrent/conf/users/${username}/config.php
  sed -i "s/YYY/${AUTODLPORT}/g" /srv/rutorrent/conf/users/${username}/config.php
  sed -i "s/ZZZ/\"${AUTODLPASSWORD}\"/g" /srv/rutorrent/conf/users/${username}/config.php
}

# function to install pure-ftpd (31)
function _installftpd() {
  apt-get purge -y vsftpd pure-ftpd >>"${OUTTO}" 2>&1
  apt-get autoremove >>"${OUTTO}" 2>&1
  apt-get install -y vsftpd >>"${OUTTO}" 2>&1
}

# function to configure pure-ftpd (32)
function _ftpdconfig() {
  cp ${local_setup}templates/openssl.cnf.template /root/.openssl.cnf

  openssl req -config /root/.openssl.cnf -x509 -nodes -days 365 -newkey rsa:1024 -keyout /etc/ssl/private/vsftpd.pem -out /etc/ssl/private/vsftpd.pem >/dev/null 2>&1

  cp ${local_setup}templates/vsftpd.conf.template /etc/vsftpd.conf

  # Enabling passive mode
  sed -i 's/^\(pasv_min_port=\).*/\110090/' /etc/vsftpd.conf
  sed -i 's/^\(pasv_max_port=\).*/\110100/' /etc/vsftpd.conf
  echo "pasv_address="$IP >> /etc/vsftpd.conf
  iptables -I INPUT -p tcp --destination-port 10090:10100 -j ACCEPT

  echo "" > /etc/vsftpd.chroot_list
}

# The following function makes necessary changes to Network and TZ settings needed for
# the proper functionality of the QuickBox Dashboard.
function _quickstats() {
  # Dynamically adjust to use the servers active network adapter
  printf "${IFACE}" > /srv/rutorrent/home/db/interface.txt
  printf "${username}" > /srv/rutorrent/home/db/master.txt
  # Use server timezone
  cd /usr/share/zoneinfo
  find * -type f -exec sh -c "diff -q /etc/localtime '{}' > /dev/null && echo {}" \; > ~/tz.txt
  cd ~
  LOCALE=en_GB.UTF-8
  LANG=lang_en
  sed -i "s/LOCALE/${locale}/g" /srv/rutorrent/home/inc/localize.php
  sed -i "s/LANG/${lang}/g" /srv/rutorrent/home/inc/localize.php
  #echo "  date_default_timezone_set('$(cat tz.txt)');" >> /srv/rutorrent/home/widgets/config.php
  #echo "" >> /srv/rutorrent/home/widgets/config.php
  #echo "?>" >> /srv/rutorrent/home/widgets/config.php
  if [[ ${primaryroot} == "home" ]]; then
    cd /srv/rutorrent/home/widgets && rm disk_data.php
    mv disk_datah.php disk_data.php
    chown -R www-data:www-data /srv/rutorrent/home/widgets
  else
    rm /srv/rutorrent/home/widgets/disk_datah.php
  fi
}

function _quickconsole() {
  PUBLICIP=$(ip route get 8.8.8.8 | awk 'NR==1 {print $NF}')

cat >/etc/profile<<EOF
echo " Welcome Back !"
echo "    * Dashboard:  https://${PUBLICIP}"
echo "    * Support:    https://plaza.quickbox.io"
echo "    * Donate:     https://quickbox.io/donate"
echo ""
EOF

  apt-get -y install shellinabox >>"${OUTTO}" 2>&1;

  cp ${local_setup}templates/sysd/shellinabox.template /etc/systemd/system/shellinabox.service
  cp ${local_setup}templates/quickconsole/00_QuickConsole.css.template /etc/shellinabox/options-enabled/00_QuickConsole.css
  cp ${local_setup}templates/web-console.conf.template /etc/apache2/sites-enabled/${username}.console.conf

  sed -i "s/PUBLICIP/${PUBLICIP}/g" /etc/apache2/sites-enabled/${username}.console.conf
  sed -i "s/USER/${username}/g" /etc/apache2/sites-enabled/${username}.console.conf

  chmod +x /etc/shellinabox/options-enabled/00_QuickConsole.css
  chmod 777 /etc/shellinabox/options-enabled/00_QuickConsole.css

  systemctl enable shellinabox.service >/dev/null 2>&1
  systemctl stop shellinabox.service >/dev/null 2>&1
  systemctl daemon-reload >/dev/null 2>&1
  systemctl start shellinabox.service >/dev/null 2>&1

}

# seedbox boot for first user (35)
function _boot() {
  #if [[ $cron == yes ]]; then
  #  touch /install/.cron.lock
  #  command1="*/1 * * * * /home/${username}/.startup >/dev/null 2>&1"
  #  cat <(fgrep -iv "${command1}" <(sh -c 'sudo -u ${username} crontab -l' >/dev/null 2>&1)) <(echo "${command1}") | sudo -u ${username} crontab -
  #elif [[ $cron == no ]]; then
  cp ${local_setup}templates/sysd/rtorrent.template /etc/systemd/system/rtorrent@.service >/dev/null 2>&1
  cp ${local_setup}templates/sysd/autodlirssi.template /etc/systemd/system/irssi@.service >/dev/null 2>&1
  cp ${local_setup}templates/sysd/deluged.template /etc/systemd/system/deluged@.service >/dev/null 2>&1
  cp ${local_setup}templates/sysd/deluge-web.template /etc/systemd/system/deluge-web@.service >/dev/null 2>&1
  systemctl enable {rtorrent,irssi,deluged,deluge-web}@${username} >/dev/null 2>&1
  systemctl start {rtorrent,irssi,deluged,deluge-web}@${username} >/dev/null 2>&1
  #fi

  echo "*/1 * * * * root bash /usr/local/bin/quickbox/system/set_interface" > /etc/cron.d/set_interface
}

# function to set permissions on first user (36)
function _perms() {
  chown -R ${username}.${username} /home/${username}/ >>"${OUTTO}" 2>&1
  sudo -u ${username} chmod 755 /home/${username}/ >>"${OUTTO}" 2>&1
  chmod +x /etc/cron.daily/denypublic >/dev/null 2>&1
  chmod 777 /home/${username}/.sessions >/dev/null 2>&1
  chown -R chown -R www-data:www-data /srv/rutorrent/home >/dev/null 2>&1
  if [[ ${tr} == "yes" ]]; then
	chown -R ${username}:debian-transmission /home/${username}/torrents/transmission >/dev/null 2>&1
	service transmission-daemon reload >>"${OUTTO}" 2>&1
  fi
}

function _insbbr() {
  cd /tmp
  cp ${local_setup}sources/BBR/BBR.sh .
  chmod a+x BBR.sh
  bash BBR.sh -f v4.11.12 >>"${OUTTO}" 2>&1
  cd
}

function _insbcm() {
  mkdir -p ${local_setup}/bcm
  cd ${local_setup}/bcm
  git clone git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git >>"${OUTTO}" 2>&1
  mkdir -p /lib/firmware/bnx2/
  cp -rf ${local_setup}/bcm/linux-firmware/bnx2/ /lib/firmware
}
################################################################################
#   //BEGIN UNUSED FUNCTIONS//
################################################################################
# ask for bash or lshell function ()
# Heads Up: lshell is disabled for the initial user on install as your first user
# should not be limited in shell. Additional created users are automagically
# added to a limited shell environment.
function _askshell() {
  #echo -ne "${yellow}Set user shell to lshell?${normal} (Default: ${red}N${normal}): "; read responce
  #case $responce in
  #  [yY] | [yY][Ee][Ss] ) theshell="/usr/bin/lshell" ;;
  #  [nN] | [nN][Oo] | "" ) theshell="/bin/bash" ;;
  #  *) theshell="yes" ;;
  #esac
  echo -ne "${bold}${yellow}Add user to /etc/sudoers${normal} [${green}y${normal}]es or [n]o: "; read answer
  case $answer in
    [yY] | [yY][Ee][Ss] | "" ) sudoers="yes" ;;
    [nN] | [nN][Oo] ) sudoers="no" ;;
    *) sudoers="yes" ;;
  esac
}

# function to create ssl cert for pure-ftpd ()
function _pureftpcert() {
  /bin/true
}
################################################################################
#   //END UNUSED FUNCTIONS//
################################################################################

# function to show finished data (37)
function _finished() {
  ip=$(ip route get 8.8.8.8 | awk 'NR==1 {print $NF}')
  echo
  echo
  echo -e " ${black}${on_green}    [quickbox] Seedbox & GUI Installation Completed    ${normal} "
# echo -e "        ${standout}    INSTALLATION COMPLETED in ${FIN}/min    ${normal}             "
  echo;echo
  echo "  Valid Commands:  "
  echo '  -------------------'
  echo
  echo -e " ${green}createSeedboxUser${normal} - creates a shelled seedbox user"
  echo -e " ${green}deleteSeedboxUser${normal} - deletes a created seedbox user and their directories"
  echo -e " ${green}changeUserpass${normal} - change users SSH/FTP/ruTorrent password"
  echo -e " ${green}setdisk${normal} - set your disk quota for any given user"
  echo -e " ${green}showspace${normal} - shows the amount of space used by all users on the server"
  echo -e " ${green}reload${normal} - restarts your seedbox services, i.e; rtorrent & irssi"
  echo -e " ${green}upgradeBTSync${normal} - upgrades BTSync when new version is available"
  echo -e " ${green}upgradeOmbi${normal} - upgrades Ombi when new version is available"
  echo -e " ${green}upgradePlex${normal} - upgrades Plex when new version is available"
  echo -e " ${green}box install letsencrypt${normal} - installs a valid SSL certificate to be used with "
  echo -e "                           a valid domain name. "
  echo -e " ${green}box${normal} - type 'box -h' for a summary of how to use box!"
  echo;echo;echo
  echo '################################################################################################'
  echo "#   Seedbox can be found at https://${username}:${passwd}@${ip} "
  echo "#   ${cyan}(Also works for FTP:5757/SSH:$sshport)${normal}"
  echo "#   If you need to restart rtorrent/irssi, you can type 'reload'"
  echo "#   https://${username}:${passwd}@${ip} (Also works for FTP:5757/SSH:$sshport)" > ${username}.info
  echo "#   Reloading: ${green}sshd${normal}, ${green}apache${normal}, ${green}memcached${normal}, ${green}php7.0${normal}, ${green}vsftpd${normal} and ${green}fail2ban${normal}"
  echo '################################################################################################'
  echo

cat >/root/information.info<<EOF
  Seedbox can be found at https://${username}:${passwd}@${ip} (Also works for FTP:5757/SSH:$sshport)
  If you need to restart rtorrent/irssi, you can type 'reload'
  https://${username}:${passwd}@${ip} (Also works for FTP:5757/SSH:$sshport)
EOF
  rm -rf "$0" >>"${OUTTO}" 2>&1
    for i in ssh apache2 php7.0-fpm vsftpd fail2ban quota memcached cron; do
      service $i restart >>"${OUTTO}" 2>&1
      systemctl enable $i >>"${OUTTO}" 2>&1
    done
  rm -rf /root/tmp/

endtime=$(date +%s)
timeused=$(( $endtime - $starttime ))
if [[ $timeused -gt 60 && $timeused -lt 3600 ]]; then
    timeusedmin=$(expr $timeused / 60)
    timeusedsec=$(expr $timeused % 60)
    echo -e "  ${baiqingse}${bold}The Installation took about ${timeusedmin} min ${timeusedsec} sec${normal}"
elif [[ $timeused -ge 3600 ]]; then
    timeusedhour=$(expr $timeused / 3600)
    timeusedmin=$(expr $(expr $timeused % 3600) / 60)
    timeusedsec=$(expr $timeused % 60)
    echo -e "  ${baiqingse}${bold}The Installation took about ${timeusedhour} hour ${timeusedmin} min ${timeusedsec} sec${normal}"
else
    echo -e "  ${baiqingse}${bold}The Installation took about ${timeused} sec${normal}"
fi

  echo -ne "\n  Do you wish to reboot (recommended!): (Default ${green}Y${normal})"; read reboot
  case $reboot in
    [yY] | [yY][Ee][Ss] | "") reboot                 ;;
    [nN] | [nN][Oo] ) echo "  ${cyan}Skipping reboot${normal} ... " ;;
  esac
}

clear

spinner() {
    local pid=$1
    local delay=0.25
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [${bold}${yellow}%c${normal}]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
    echo -ne "${OK}"
}

local_setup=/etc/QuickBox/setup/
local_packages=/etc/QuickBox/packages/
local_rutorrent=/etc/QuickBox/rutorrent/
local_rplugins=/etc/QuickBox/rtplugins/
local_themes=/etc/QuickBox/themes/
local_dashboard=/etc/QuickBox/dashboard/

IFACE=$(ip link show|grep -i broadcast|grep -m1 UP|cut -d: -f 2|cut -d@ -f 1|sed -e 's/ //g');
HOSTNAME1=$(hostname -s);
PORT=$(shuf -i 2000-61000 -n 1)
PORTEND=$((${PORT} + 1500))
while [[ "$(netstat -ln | grep ':'"$PORT"'' | grep -c 'LISTEN')" -eq "1" ]]; do PORT="$(shuf -i 2000-61000 -n 1)"; done
RPORT=$(shuf -i 2000-61000 -n 1)
while [[ "$(netstat -ln | grep ':'"$RPORT"'' | grep -c 'LISTEN')" -eq "1" ]]; do RPORT="$(shuf -i 2000-61000 -n 1)"; done
S=$(date +%s)
OK=$(echo -e "[ ${bold}${green}DONE${normal} ]")
genpass=$(_string)
HTPASSWD="/etc/htpasswd"
rutorrent="/srv/rutorrent/"
REALM="rutorrent"
AUTODLPASSWORD=$(_string)
AUTODLPORT=$(shuf -i 2000-61000 -n 1)
ip=$(ip route get 8.8.8.8 | awk 'NR==1 {print $NF}')
BTSYNCIP=$(ip route get 8.8.8.8 | awk 'NR==1 {print $NF}')
export DEBIAN_FRONTEND=noninteractive
cd

# QuickBox STRUCTURE
_init
_bashrc
_intro
_checkroot
_logcheck
_checkkernel
_hostname
_askquota
_askcontinue
_ssdpblock
_locale
clear

starttime=$(date +%s)

#_askservices
_askpartition
_askrtorrent
_askdeluge
_askqb
_asktr
# _askdashtheme
dash_theme=defaulted
_adduser
_askvsftpd
_denyhosts
_askfg
_askbbr

tram=$( free -m | awk '/Mem/ {print $2}' )
[[ $tram -le 2333 ]] &&  { USESWAP=Yes
echo -e "${bold}${red}Note that${normal} ${bold}Your RAM is below ${red}2333MB${jiacu}, memory may got exhausted when compiling${normal}"
echo -e "${bold}${baiqingse} 1GB Additonal swap ${normal} will be used\n" ; }

echo -e "${bold}If you want to stop, Press ${on_red}Ctrl+C${normal} ${bold}; or Press ${on_green}ENTER${normal} ${bold}to start${normal}" ; [[ ! $ForceYes == 1 ]] && read input

clear
echo
echo ""
echo "${bold}${magenta}QuickBox will now install, this may take between${normal}"
echo "${bold}${magenta}10 and 60 minutes depending on your systems specs${normal}"
echo ""
[[ $USESWAP == Yes ]] && { echo -n "Creating Swap ... " ; _use_swap & spinner $!; echo ; }
echo -n "Pulling QuickBox Ecosystem ... ";_repos & spinner $!;echo
echo -n "Updating system ... ";_updates & spinner $!;echo
echo -n "Installing all needed dependencies ... ";_depends & spinner $!;echo
echo -n "Installing openssl ... ";_openssl & spinner $!;echo
echo -n "Setting up system executables ... ";_syscommands & spinner $!;echo
echo -n "Building required user directories ... ";_skel & spinner $!;echo
if [[ ${quota} == "yes" ]]; then
echo -n "Setting up quotas for ${green}/($primaryroot)${normal} mount ... ";_qmount & spinner $!;echo
fi
echo -n "Setting up Limited Shell environment ... ";_lshell & spinner $!;echo
echo -n "Installing ffmpeg for screenshots ... ";_ffmpeg & spinner $!;echo
_apachesudo
echo -n "Installing xmlrpc-c-${green}1.33.12${normal} ... ";_xmlrpc & spinner $!;echo
echo -n "Installing libtorrent-${green}$LTORRENT${normal} ... ";_libtorrent & spinner $!;echo
echo -n "Installing rtorrent-${green}$RTVERSION${normal} ... ";_rtorrent & spinner $!;echo
echo -n "Installing rutorrent into /srv ... ";_rutorrent & spinner $!;echo
echo -n "Installing rutorrent plugins ... ";_rutorrent-plugins & spinner $!;echo
echo -n "Installing deluge ... ";_deluge & spinner $!;echo
echo -n "Setting up deluge Web Reverse Proxy ... ";_insdwApache & spinner $!;echo
if [[ ${tr} == "yes" ]]; then
    echo -n "Configuring Transmisson ... ";_insTr & spinner $!;echo
    echo -n "Installing Transmisson Web Control ... ";_insTrWeb & spinner $!;echo
    echo -n "Setting up Transmission Reverse Proxy ... ";_insTrApache & spinner $!;echo
fi
echo -n "Installing qBittorrent ... ";_qbittorrent & spinner $!;echo
echo -n "Setting up qBittorrent Reverse Proxy ... ";_insqBApache & spinner $!;echo
[[ $fg == Yes ]] && { echo -n "Installing Flexget ... " ; _insfg & spinner $!; echo ; }
echo -n "Installing mktorrent from source ... ";_mktorrent & spinner $!;echo
echo -n "Installing quickbox dashboard ... ";_dashboard & spinner $!;echo
echo -n "Building system file indexer (h5ai) ... ";_fileindexer & spinner $!;echo
echo -n "Setting up seedbox.conf for apache ... ";_apacheconf & spinner $!;echo
echo -n "Fix SSL Cert for apache ... ";_fix_cert & spinner $!;echo
echo -n "Installing .rtorrent.rc for ${username} ... ";_rconf & spinner $!;echo
echo -n "Adjusting fileupload & filemanager plugins ... ";_plugins & spinner $!;echo
echo -n "Installing autodl-irssi ... ";_autodl & spinner $!;echo
echo -n "Making ${username} directory structure ... ";_makedirs & spinner $!;echo
echo -n "Writing ${username} rutorrent config.php file ... ";_ruconf & spinner $!;echo
echo -n "Installing vsftpd ... ";_installftpd & spinner $!;echo
echo -n "Setting up vsftpd ... ";_ftpdconfig & spinner $!;echo
# 安装我自己的脚本
for JIAOBEN in jietu bdinfo bluray mingling guazai ipv6 xiansu zuozhong bdjietu ; do wget -qO /usr/local/bin/$JIAOBEN https://github.com/Aniverse/inexistence/raw/master/00.Installation/script/$JIAOBEN && chmod +x /usr/local/bin/$JIAOBEN ; done
_quickstats;
_quickconsole;
echo -n "Setting irssi/rtorrent to start on boot ... ";_boot & spinner $!;echo;
echo -n "Setting permissions on ${username} ... ";_perms & spinner $!;echo;
if [[ ${bbr} == "yes" ]]; then
    echo -n "install BBR ... ";_insbbr & spinner $!;echo
fi
if lspci | grep -i bcm > /dev/null; then
    echo -n "Installing firmware for BCM NIC ... ";_insbcm & spinner $!;echo
fi
cd
E=$(date +%s)
DIFF=$(echo "$E" - "$S"|bc)
FIN=$(echo "$DIFF" / 60|bc)

[[ $USESWAP == Yes ]] && _disable_swap
clear


_finished
